# Generated by Django 4.1.3 on 2022-11-20 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Catagory',
            new_name='category',
        ),
    ]
